# NOTE: Read the Docs deployment is still required.
# This file is kept on purpose so we don't forget to reconfigure it for VitePress.
# TODO: Replace the placeholder build step below with the real VitePress build
#       (likely Node.js install + `vitepress build` output path).
#       Once VitePress is wired up, remove these comments.

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - echo "TODO: configure Read the Docs build for VitePress"

# No Sphinx config here by design.
# The VitePress setup will define how and where the static site is built.
