version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "22"
  jobs:
    install:
      - npm install
    build:
      html:
        - npx vitepress build docs
        - mkdir -p $READTHEDOCS_OUTPUT/
        - mv docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
