from collections.abc import Mapping

from fontTools.ttLib.ttGlyphSet import _TTGlyph, _TTGlyphSet

class BasePen:
    glyphSet: _TTGlyphSet | Mapping[str, _TTGlyph] | None

    def __init__(
        self,
        glyphSet: _TTGlyphSet | Mapping[str, _TTGlyph] | None = ...,
    ) -> None: ...
    def moveTo(self, pt: tuple[float, float]) -> None: ...
    def lineTo(self, pt: tuple[float, float]) -> None: ...
    def curveTo(self, *points: tuple[float, float]) -> None: ...
    def qCurveTo(self, *points: tuple[float, float]) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
    def _moveTo(self, pt: tuple[float, float]) -> None: ...
    def _lineTo(self, pt: tuple[float, float]) -> None: ...
    def _curveToOne(
        self,
        pt1: tuple[float, float],
        pt2: tuple[float, float],
        pt3: tuple[float, float],
    ) -> None: ...
    def _closePath(self) -> None: ...
    def _endPath(self) -> None: ...
