from collections.abc import Iterator, Mapping

class _TTGlyph:
    def draw(self, pen: object) -> None: ...

class _TTGlyphSet(Mapping[str, _TTGlyph]):
    def __getitem__(self, key: str) -> _TTGlyph: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

__all__ = ["_TTGlyph", "_TTGlyphSet"]
