name: Test

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "examples/**"
      - ".gitattributes"
      - ".gitignore"
      - "LICENSE"
      - "README.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "examples/**"
      - ".gitattributes"
      - ".gitignore"
      - "LICENSE"
      - "README.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Ruff lint
        run: uv run ruff check .

      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        torch-version: ["2.6.0", "2.7.0", "2.8.0"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run tests
        run: uv run --with "torch==${{ matrix.torch-version }}" pytest tests
