name: Test

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "examples/**"
      - "src/**"
      - "tests/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "examples/**"
      - "src/**"
      - "tests/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --only-dev

      - name: Ruff lint
        run: uv run --no-sync ruff check .

      - name: Ruff format
        run: uv run --no-sync ruff format --diff .

  typecheck:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Run mypy
        run: uv run mypy src tests examples

  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        torch-version: ["2.6", "2.7", "2.8"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Run tests
        run: uv run --with "torch==${{ matrix.torch-version }}" pytest tests
