name: Release

on:
  push:
    tags:
      - v*

jobs:
  run:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      - name: Build
        run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with "torch>=2.8" --with dist/*.whl tests/smoke_test.py

      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with "torch>=2.8" --with dist/*.tar.gz tests/smoke_test.py

      - name: Publish
        run: uv publish
